### PR TITLE
Fix for #186. Implemented custom responds to selector that works fine with x64 simulators on iOS 9

### LINKED ISSUE #186: iOS 9 Crashes with styleClass All Over
I just fired up my Pixate-enabled app in the iOS 9 simulator, and it crashes all over the place with messages like:

    -[UITextField preventStyling]: unrecognized selector sent to instance 0x7fa8b96d6330
    
    Failed to set (styleClass) user defined inspected property on (UITextField): -[UITextField preventStyling]: unrecognized selector sent to instance 0x7fa8b96d6330

and...

    -[UISearchBarTextField preventStyling]: unrecognized selector sent to instance 0x7fda5af39350

Anyone know why this `preventStyling` thing is creating issues? I don't explicitly using it anywhere in my code. It appears to get called when using `styleClass`.

### PR DESCRIPTION
**Pull request by anton-matosov**
Fixes #186

### CODE REVIEW

**Comment by Pitsko** [comment]
Good fix, thank you

When it can be merged ?

**Comment by Pitsko** [comment]
Actually fix doesn't work. For example it is not possible to define keyboard type for inputs field
also sometimes app crashes with error:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Class UIView doesn't fit for subclassing.'

**Comment by anton-matosov** [comment]
Is it not working with 64 bit simulator or any device?

Regarding assertion in UIView I am not quite sure if it is related to the fix in anyway.

**Comment by anton-matosov** [comment]
Is it not working with 64 bit simulator or any device?

Regarding assertion in UIView I am not quite sure if it is related to the fix in anyway.

**Comment by anton-matosov** [comment]
Is it not working with 64 bit simulator or any device?

Regarding assertion in UIView I am not quite sure if it is related to the fix in anyway.

**Comment by anton-matosov** [comment]
The project seems to be dead, so it might not be ever merged.

**Comment by Pitsko** [comment]
Yes, you are right. My issue was not related to this fix

**Pull request closed without merging**
